config/routes.rb
CabanaClub::Application.routes.draw do

  resources :userswimlessons


  resources :swim_lessons


  resources :staticpages


  resources :member_payments


  resources :members


  resources :swim_teams


  resources :payments


  resources :meeting_notes

  match "newMN" => "meeting_notes#newMN", :as => "newMN"

  resources :meetings


  resources :people


  resources :password_resets

  resources :contacts


  match '/about' => "users#about", :as => "about"
  match '/admin' => "users#admin", :as => "admin"
  match '/payment/payments_made' => "payments#payments_made", :as => "payments_made"
  match '/add_item_to_shopping_cart' => 'users#add_item_to_shopping_cart', :via => :post
  match '/remove_item_from_shopping_cart' => 'users#remove_item_from_shopping_cart', :via => :post
  match '/remove_all_items_from_shopping_cart' => 'users#remove_all_items_from_shopping_cart', :via => :post
  match '/membership' => "users#membership", :as => "membership"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#home"

  resources :users
  resources :sessions
  resources :accounts

  get "get_accounts" => "accounts#get_accounts", :as => "get_accounts"

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :description, :meeting_date, :title

  has_many :meeting_notes, :dependent => :destroy

  def meeting_name_date
  	return "#{self.meeting_date.strftime("%B %Y") if !self.meeting_date.nil?} - #{self.title}"
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :require_admin, :except => [:index, :show]
  # GET /meetings
  # GET /meetings.json
  def index

    @staticpage = Staticpage.find(:first, :conditions => ["page_name = ?", "MeetingNotes"]) 
    
    @meetings = Meeting.find(:all, :order => ["meeting_date desc"])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_path, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to meetings_path, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :class => 'input-block-level', :placeholder => 'Title' %>
  </div>
  <div class="field">
    <%= f.text_area :description, :class => 'input-block-level', :placeholder => 'Description of this meeting' %>
  </div>
  <div class="field">
    <%= f.text_field :meeting_date, :class => 'input-block-level', :value => Date.today %>
  </div>
  <div class="actions save_button_wrapper">
    <%= f.submit 'Save', :class => 'btn btn-main' %>
  </div>
<% end %>

app/views/meetings/_meeting_notes_box.html.erb
<div class="meeting_note_wrapper" style="padding:15px 10px 10px 20px;">
  <div class="meeting_note_left_column">
    <%= mn.updated_at.in_time_zone("Pacific Time (US & Canada)").strftime("%B %d, %Y %H:%M %p") %>
  </div>
  <div class="meeting_note_right_column">
    <%= simple_format(mn.description) %>
  </div>
</div>

app/views/meetings/edit.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      Editing Meeting
    </div>
  </div>


  <%= render 'form' %>

</div>

app/views/meetings/index.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      <% if !@staticpage.nil? %>
        <%= @staticpage.page_title %>
      <% else %>
        Meeting Notes
      <% end %>
    </div>
    <% if is_admin? %>
      <div class="pull-right">
        <%= link_to "New Meeting", new_meeting_path, :class => "btn btn-small btn-success" %>
        <% if @staticpage.nil? %>
          <%= link_to "Edit Page", new_staticpage_path(:page_name => "MeetingNotes", :page_url => "meetings"), :class => "btn btn-small btn-success" %>
        <% else %>
          <%= link_to "Edit Page", edit_staticpage_path(@staticpage), :class => "btn btn-small btn-success" %>
          <%= link_to 'Remove Custom Page', @staticpage, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if !@staticpage.nil? %>
    <div style="margin:15px 0;">
      <%= image_tag @staticpage.static_page_photo.url(:small), :class => "bordered_image static_page_photo" if @staticpage.static_page_photo? %>
      <%= simple_format(@staticpage.page_body) %>
    </div>
  <% end %>


  <% @meetings.each do |meet| %>
    <div class="meeting_wrapper" style="overflow:auto;">
      <div class="meeting_header">
        <%= link_to "#{meet.meeting_name_date}", "#", :id => "#{meet.id}", :class => "meeting_name" %>
        <% if is_admin? %>
          <div class="pull-right">
            <%= link_to "New Meeting Notes", meeting_path(meet), :class => "btn btn-small btn-success" %> &nbsp;&nbsp; <%= link_to 'Edit', edit_meeting_path(meet), :class => "btn btn-small btn-warning" %> &nbsp;&nbsp; <%= link_to 'Delete', meet, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %>
          </div>
        <% end %>
      </div>

      <div class="meeting_notes_wrapper" id="mn_<%= meet.id %>" style="display:none;">
        <% if !meet.description.blank? %>
          <div class="meeting_description">
            <div class="meeting_note_left_column">
              Description: 
            </div>
            <div class="meeting_note_right_column">
              <%= simple_format(meet.description) %>
            </div>
          </div>
        <% end %>
        <% meet.meeting_notes.order(&:updated_at).each do |mn| %>
          <%= render :partial => 'meeting_notes_box', :locals => { :mn => mn } %>
        <% end %>

        <% if meet.meeting_notes.empty? %>
          <div class="meeting_note_wrapper">
            <div class="meeting_note_left_column">
              
            </div>
            <div class="meeting_note_right_column">
              No notes have been added for this meeting.
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if @meetings.last.id != meet.id %>
      <div class="divider_div">
      </div>
    <% end %>

  <% end %>

</div>

<script type="text/javascript">

$(document).ready(function(){
  $(".meeting_name").click(function(){
    cu_id = $(this).attr("id");
    $("#mn_" + cu_id).toggle();
  });
})

</script>

app/views/meetings/new.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      New Meeting
    </div>
  </div>


  <%= render 'form' %>

</div>

app/views/meetings/show.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      
    </div>

    <div class="meeting_header">
      <%= @meeting.meeting_name_date %>
    </div>

      <div class="meeting_notes_wrapper">
        <% if !@meeting.description.blank? %>
          <div class="meeting_description">
            <div class="meeting_note_left_column">
              Description: 
            </div>
            <div class="meeting_note_right_column">
              <%= simple_format(@meeting.description) %>
            </div>
          </div>
        <% end %>
      </div>

  </div>

  
  <div class="large_sub_header sub_header_padding" style="padding-left:20px; padding-right:20px;">
	<%= form_tag newMN_path, :method => 'post', :id => "new_meeting_notes" do %>
	  <%= hidden_field_tag :meeting_id, @meeting.id %>
	  <div class="field">
	    <%= text_area_tag :description, '', :class => 'input-block-level meeting_description', :placeholder => 'Meeting Note', :id => "meeting_description_text" %>
	  </div>
	  <div>
	  	<%= submit_tag 'Save', :class => 'save_meeting_note btn btn-main' %>
  	  </div>
	<% end %>
  </div>

  <div class="meeting_notes_wrapper" id="all_meeting_notes">
    <% @meeting.meeting_notes.order("created_at desc").each do |mn| %>
      <%= render :partial => 'meeting_notes_box', :locals => { :mn => mn } %>
    <% end %>
  </div>

</div>

<script type="text/javascript">

$(document).ready(function(){
  
  $('.save_meeting_note').click(function(){
    
    $.post($("#new_meeting_notes").attr("action"), $("#new_meeting_notes").serialize(), null, null);

    $('#meeting_description_text').val("");

    return false;
  });

});

</script>