config/routes.rb
CabanaClub::Application.routes.draw do

  resources :userswimlessons


  resources :swim_lessons


  resources :staticpages


  resources :member_payments


  resources :members


  resources :swim_teams


  resources :payments


  resources :meeting_notes

  match "newMN" => "meeting_notes#newMN", :as => "newMN"

  resources :meetings


  resources :people


  resources :password_resets

  resources :contacts


  match '/about' => "users#about", :as => "about"
  match '/admin' => "users#admin", :as => "admin"
  match '/payment/payments_made' => "payments#payments_made", :as => "payments_made"
  match '/add_item_to_shopping_cart' => 'users#add_item_to_shopping_cart', :via => :post
  match '/remove_item_from_shopping_cart' => 'users#remove_item_from_shopping_cart', :via => :post
  match '/remove_all_items_from_shopping_cart' => 'users#remove_all_items_from_shopping_cart', :via => :post
  match '/membership' => "users#membership", :as => "membership"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#home"

  resources :users
  resources :sessions
  resources :accounts

  get "get_accounts" => "accounts#get_accounts", :as => "get_accounts"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :account_id, :email, :fname, :lname, :phone_number, :password, :password_confirmation, :admin, :address, :city, :state, :zip_code, :super_admin, :active, :customer_stripe_token
  
  belongs_to :account
  has_many :payments

  attr_accessor :password
  before_save :encrypt_password

  before_create { generate_token(:auth_token) }
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip_code
  #validates_presence_of :account_id

  has_many :membershippayments
  has_many :member_payments, :through => :membershippayments

  has_many :userswimteams
  has_many :swim_teams, :through => :userswimteams

  has_many :userswimlessons
  has_many :swim_lessons, :through => :userswimlessons

  
  scope :reset_token, lambda { |token| where("password_reset_token = ?", token) }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def full_name
    return self.fname + ' ' + self.lname
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    CabanaclubMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.base64.tr("+/", "-_")
    end while User.exists?(column => self[column])
  end

  def user_address
    user_address = self.address + " " + self.city + ", " + self.state + " " + self.zip_code
    return user_address
  end

  def save_also_to_stripe
    begin
      customer = Stripe::Customer.create(description: user_address, email: email)
      self.customer_stripe_token = customer.id
      save!
    rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while creating customer: #{e.message}"
      puts "message :: #{e.message}"
      errors.add :base, "There was a problem with your credit card."
      false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin, :only => [:index, :admin]
  before_filter :require_login, :only => [:add_item_to_shopping_cart, :remove_item_from_shopping_cart, :remove_all_items_from_shopping_cart]

  def home
  end

  def about
  end

  def admin
  end

  def membership
    @staticpage = Staticpage.find(:first, :conditions => ["page_name = ?", "Membership"]) 
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.find(:all, :conditions => ["active = ?", true])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @staticpage = Staticpage.find(:first, :conditions => ["page_name = ?", "UserPayment"]) 
    
    if is_admin?
      @user = User.find(params[:id])
    else
      @user = User.find(current_user)
    end

    @payments_need_to_make = nil

    if @user == current_user

      users_payments = current_user.membershippayments.all(:select => :member_payment_id).collect(&:member_payment_id)

      if users_payments.length > 0
        @payments_need_to_make = MemberPayment.find(:all, :conditions => ["id not in (?)", users_payments])
      else
        @payments_need_to_make = MemberPayment.find(:all)
      end
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @staticpage = Staticpage.find(:first, :conditions => ["page_name = ?", "SignUp"]) 
    @user = User.new
    @accounts = Account.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    if is_admin?
      @user = User.find(params[:id])
    else
      @user = User.find(current_user)
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save_also_to_stripe
        cookies[:auth_token] = @user.auth_token
        format.html { redirect_to @user, notice: 'Thanks for Signing up.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    if is_admin?
      @user = User.find(params[:id])
    else
      @user = User.find(current_user)
      @user.admin = @user.admin
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Your account has been updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if is_admin?
      @user = User.find(params[:id])
    else
      @user = User.find(current_user)
    end

    @user.active=false

    @user.save

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def add_item_to_shopping_cart
    add_to_shopping_cart(params[:model_id], params[:model_name])

    render :nothing => true
  end

  def remove_item_from_shopping_cart
    delete_one_item_from_shopping_cart(params[:model_id], params[:model_name])

    render :nothing => true
  end

  def remove_all_items_from_shopping_cart
    delete_all_from_shopping_cart

    render :nothing => true
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :account_id, :id => "account_id" %>

  <div>
    
    <!-- <div style="width:46%; display:inline-block;"> -->
    <div>
      <div class="field">
        <%= f.text_field :email, :class => 'input-block-level', :placeholder => "Email" %>
      </div>
      <div class="field">
        <%= f.text_field :fname, :class => 'input-block-level', :placeholder => "First Name" %>
      </div>
      <div class="field">
        <%= f.text_field :lname, :class => 'input-block-level', :placeholder => "Last Name" %>
      </div>
      <div class="field">
        <%= f.text_field :phone_number, :class => 'input-block-level', :placeholder => 'Phone Number' %>
      </div>
      <div class="field">
        <%= f.text_field :address, :class => 'input-block-level', :placeholder => 'Address' %>
      </div>
      <div class="field">
        <%= f.text_field :city, :class => 'input-block-level', :placeholder => 'City' %>
      </div>
      <div class="field">
        <%= f.text_field :state, :class => 'input-block-level', :placeholder => 'State' %>
      </div>
      <div class="field">
        <%= f.text_field :zip_code, :class => 'input-block-level', :placeholder => 'Zip Code' %>
      </div>
      <div class="field">
        <%= f.password_field :password, :class => 'input-block-level', :placeholder => 'Password' %>
      </div>
      <div class="field">
        <%= f.password_field :password_confirmation, :class => 'input-block-level', :placeholder => 'Password Confirmation' %>
      </div>

      <% if is_admin? %>
        <div class="field" style="margin-bottom:10px;">
          <%= f.check_box :admin %> Admin
        </div>
      <% end %>


  <div class="actions">
    <%= f.submit 'Sign Up', :class => 'btn btn-main' %>
  </div>
<% end %>

    </div>
<!-- 
    <% if params[:action] != "edit" %>
    <div style="margin-left:20px;width:49%; display:inline-block; vertical-align:top;">
      <%= form_tag get_accounts_path, :method => 'get', :id => "accounts_search" do %>
        <div>
          <h5>
            Select An Address:
          </h5>
        </div>
        <div>
          <%= text_field_tag :search, params[:search], :placeholder => "Search for an address" %>
        </div>
        <div id="accounts"><%= render 'accounts/accounts' %></div>
      <% end %>
    </div>
    <% end %>
  
  </div>


<% if params[:action] != "edit" %>
<script type="text/javascript">

$(document).ready(function(){
  $("input[name=account]:radio").change(function () {
    setAccountId();
  });

  $( "#new_user" ).submit(function( event ) {
    setAccountId();
  });

  setAccountId();

});

function setAccountId(){
  var selected = $("input[name=account]:radio:checked");
  $("#account_id").val(selected.val());
}

</script>
<% end %>
 -->

app/views/users/about.html.erb
<div class="bordered_wrapper">
  <h3>
    About The Del Prado Cabana Club
  </h3>
  
  <div class="row">
    <div class="span11">
      <h4>Cheese ipsum</h4>
      <p>
        Emmental melted cheese blue castello. Cheese slices danish fontina cut the cheese caerphilly bavarian bergkase stinking bishop cut the cheese cream cheese. Blue castello mozzarella paneer cut the cheese lancashire rubber cheese edam monterey jack. Boursin paneer cottage cheese pepper jack port-salut boursin fondue lancashire. Rubber cheese stilton cottage cheese cauliflower cheese fromage frais cheesecake port-salut bavarian bergkase. Cheddar monterey jack.
      </p>

      <p>
        Monterey jack cottage cheese boursin. Bocconcini say cheese ricotta fromage frais airedale taleggio squirty cheese goat. Swiss who moved my cheese macaroni cheese smelly cheese feta dolcelatte cheesy feet cheese strings. Babybel halloumi red leicester manchego emmental the big cheese cheesy grin bocconcini. Fromage frais mascarpone camembert de normandie cheese and biscuits cheesecake everyone loves cauliflower cheese stinking bishop. Swiss monterey jack cheese slices feta.
      </p>
    </div>
 
  </div>
</div>

app/views/users/admin.html.erb
<div class="bordered_wrapper">
  <h3>
    Del Prado Cabana Club Admin Page
  </h3>
  
  <div class="row">
    <div class="span11">

      <table class="table table-condensed">
        <tr>
          <td><%= link_to "Users", users_path() %></td>
        </tr>
        <tr>
          <td><%= link_to "Lifeguards", people_path(:type => "lifeguard") %></td>
        </tr>
        <tr>
          <td><%= link_to "Board", people_path(:type => "board") %></td>
        </tr>
        <tr>
          <td><%= link_to "Meeting Notes", meetings_path() %></td>
        </tr>
        <tr>
          <td><%= link_to "Swim Teams", swim_teams_path() %></td>
        </tr>
        <tr>
          <td><%= link_to "Membership Payments", member_payments_path() %></td>
        </tr>
        <tr>
          <td><%= link_to "Membership Page", membership_path() %></td>
        </tr>
        <tr>
          <td><%= link_to "Payments Made", payments_made_path() %></td>
        </tr>
        <tr>
          <td><%= link_to "Sign Up Page", sign_up_path() %></td>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      Editing user
    </div>
  </div>


  <%= render 'form' %>
</div>

app/views/users/home.html.erb
<div class="hero-unit">
  <div style="text-align:center;margin-bottom:10px;color:#777;">
    <h1 style="font-weight:300;">Del Prado Cabana Club</h1>
  </div>
  <div style="margin-top:20px;">
    <div class="span6">
      <%= image_tag('CabanaClubFrontView.png') %>
    </div>
    <div class="span5" style="font-size:18px; font-weight:300; vertical-align:top;">
      <div style="font-size:25px; font-weight:600;">
        Come Swimming!
      </div>
      <div style="margin-top:10px;">
        Sugar plum marshmallow apple pie cheesecake chocolate cake soufflé applicake oat cake. Sweet roll muffin sugar plum candy canes tart gummi bears brownie pastry.
      </div>
      <% if !current_user %>
      <div style="text-align:center; margin-top:10px;">
        <%= link_to "Sign Up Now", membership_path(), :class => 'sign_up_tally btn btn-large btn-main' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="span4">
    <h4>Neque porro</h4>
    <p>
      Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.
    </p>
  </div>
   
  <div class="span4">
    <h4>Fugiat duis</h4>
    <p>
      Fugiat duis turducken ea. In biltong corned beef ham hock minim tongue sunt short loin capicola culpa tail. Reprehenderit strip steak tongue do, rump quis pork excepteur chicken ribeye.
    </p>
  </div>
   
  <div class="span4">
    <h4>Prosciutto pork chop</h4>
    <p>
      Dolor adipisicing short loin shank. Shank aliquip salami do eiusmod kielbasa pork frankfurter pariatur t-bone pastrami prosciutto pork chop ham.
    </p>
  </div>
</div>

<% if !current_user %>
  <div style="text-align:center; margin-top:10px;">
    <%= link_to "Sign Up Now", membership_path(), :class => 'sign_up_tally btn btn-large btn-main' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="bordered_wrapper">
  <h3>
    Users
  </h3>
  
  <div class="row">
    <div class="span11">

      <table class="table table-condensed">

        <tr>
          <th>Email</th>
          <th>Fname</th>
          <th>Lname</th>
          <th>Phone number</th>
          <th>Admin</th>
          <th></th>
          <th></th>
        </tr>

        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.fname %></td>
            <td><%= user.lname %></td>
            <td><%= user.phone_number %></td>
            <td><%= user.admin ? 'Yes' : '' %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>

      </table>
    </div>

  </div>
</div>

app/views/users/membership.html.erb
<div class="bordered_wrapper" style="border:none;">

  <div class="header_wrapper">
    <div class="main_header">
      <% if !@staticpage.nil? %>
        <%= @staticpage.page_title %>
      <% else %>
        Membership
      <% end %>
    </div>

    <div class="pull-right">
      <% if is_admin? %>
        <% if @staticpage.nil? %>
          <%= link_to "Edit Page", new_staticpage_path(:page_name => "Membership", :page_url => "membership"), :class => "btn btn-small btn-success" %>
        <% else %>
          <%= link_to "Edit Page", edit_staticpage_path(@staticpage), :class => "btn btn-small btn-success" %>
          <%= link_to 'Remove Custom Page', @staticpage, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %>
        <% end %>
      <% end %>
      <% if !current_user %>
        <%= link_to "Sign Up Now", sign_up_path(), :class => 'sign_up_tally btn btn-small btn-main' %>
      <% end %>
    </div>
  </div>

  <% if !@staticpage.nil? %>
    <% if @staticpage.static_page_photo? %>
      <div style="margin:15px 0; text-align:center;">
        <%= image_tag @staticpage.static_page_photo.url(:medium), :class => "bordered_image" %>
      </div>
    <% end %>
    <div>
      <%= simple_format(@staticpage.page_body) %>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      Sign Up
    </div>
  </div>


  <%= render 'form' %>

	<div style="text-align:center;">
		<%= link_to "or Sign In", log_in_path() %>
	</div>

</div>

app/views/users/show.html.erb
<div class="bordered_wrapper">

    <div class="header_wrapper">
      <div class="main_header">
        <%= @user.full_name %>
      </div>
      <div class="pull-right">
        <%= link_to "Edit", edit_user_path(@user), :class => "btn btn-small btn-warning" %>
        <%= link_to "Payment History", payments_path(), :class => "btn btn-small btn-success" %>
      </div>
    </div>

    <div class="meeting_wrapper" style="overflow:auto;">
      
      <div class="meeting_description">
        <div class="meeting_note_left_column">
          Email: 
        </div>
        <div class="meeting_note_right_column">
          <%= @user.email %>
        </div>
      </div>

      <div class="divider_div"></div>

      <div class="meeting_description">
        <div class="meeting_note_left_column">
          Phone Number: 
        </div>
        <div class="meeting_note_right_column">
          <%= @user.phone_number %>
        </div>
      </div>

      <div class="divider_div"></div>

      <div class="meeting_description">
        <div class="meeting_note_left_column">
          Account: 
        </div>
        <div class="meeting_note_right_column">
          <%= @user.address %><br/>
          <%= @user.city %>, <%= @user.state %> <%= @user.zip_code %>
        </div>
      </div>

      <div class="divider_div"></div>

    </div>

    

    <% if !@payments_need_to_make.empty? %>
      <div class="header_wrapper" style="margin-top:50px;">
        <div class="main_header">
          <% if !@staticpage.nil? %>
            <%= @staticpage.page_title %>
          <% else %>
            Payments You Owe:
          <% end %>
        </div>
        <% if is_admin? %>
          <div class="pull-right">
            <% if @staticpage.nil? %>
              <%= link_to "Edit Page", new_staticpage_path(:page_name => "UserPayment", :page_url => "current_user"), :class => "btn btn-small btn-success" %>
            <% else %>
              <%= link_to "Edit Page", edit_staticpage_path(@staticpage), :class => "btn btn-small btn-success" %>
              <%= link_to 'Remove Custom Page', @staticpage, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %>
            <% end %>
          </div>
        <% end %>
      </div>



      <% if !@staticpage.nil? %>
        <div style="margin:15px 0;">
          <%= image_tag @staticpage.static_page_photo.url(:small), :class => "bordered_image static_page_photo" if @staticpage.static_page_photo? %>
          <%= simple_format(@staticpage.page_body) %>
        </div>
      <% end %>

      <div class="meeting_wrapper" style="overflow:auto;">
        <table class="table table-condensed">

          <tr>
            <th>Check to Pay</th>
            <th>Name</th>
            <th style="text-align:right;">Cost</th>
          </tr>

          <% @payments_need_to_make.each do |member_payment| %>
            <tr>
              <td><input class="register_for_class" id="<%= member_payment.id.to_s + ',' + member_payment.class.name %>" type="checkbox" /></td>
              <td><%= member_payment.name %></td>
              <td style="text-align:right;"><%= number_to_currency(member_payment.cost) %></td>
            </tr>
          <% end %>
        </table>
      </div>

      <div class="pull-right">
        <%= link_to 'CheckOut', new_payment_path(), :class => "btn btn-small btn-success" %>
      </div>
    <% end %>

    

</div>