config/routes.rb
CabanaClub::Application.routes.draw do

  resources :userswimlessons


  resources :swim_lessons


  resources :staticpages


  resources :member_payments


  resources :members


  resources :swim_teams


  resources :payments


  resources :meeting_notes

  match "newMN" => "meeting_notes#newMN", :as => "newMN"

  resources :meetings


  resources :people


  resources :password_resets

  resources :contacts


  match '/about' => "users#about", :as => "about"
  match '/admin' => "users#admin", :as => "admin"
  match '/payment/payments_made' => "payments#payments_made", :as => "payments_made"
  match '/add_item_to_shopping_cart' => 'users#add_item_to_shopping_cart', :via => :post
  match '/remove_item_from_shopping_cart' => 'users#remove_item_from_shopping_cart', :via => :post
  match '/remove_all_items_from_shopping_cart' => 'users#remove_all_items_from_shopping_cart', :via => :post
  match '/membership' => "users#membership", :as => "membership"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#home"

  resources :users
  resources :sessions
  resources :accounts

  get "get_accounts" => "accounts#get_accounts", :as => "get_accounts"

end

app/models/swim_team.rb
class SwimTeam < ActiveRecord::Base
  attr_accessible :description, :end_age, :end_date, :name, :num_allowed_participants, :price_per_participant, :start_age, :start_date, :active, :start_time, :end_time, :mon, :tues, :wed, :thurs, :fri, :sat, :sun, :photo

  has_attached_file :photo, :styles => { :icon => "95x65#", :small => "150>x150" },
  :default_url => "/system/photos/default/:style/default.jpg"

  has_many :userswimteams
  has_many :users, :through => :userswimteams
end

app/controllers/swim_teams_controller.rb
class SwimTeamsController < ApplicationController
  before_filter :require_admin, :except => [:index]

  # GET /swim_teams
  # GET /swim_teams.json
  def index

    @staticpage = Staticpage.find(:first, :conditions => ["page_name = ?", "SwimTeam"]) 

    if is_admin?
      @swim_teams = SwimTeam.find(:all, :order => ["start_date asc, start_time asc"])
    else
      @swim_teams = SwimTeam.find(:all, :conditions => ["active = ? && start_date >= ?", true, Date.today], :order => ["start_date asc, start_time asc"])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @swim_teams }
    end
  end

  # GET /swim_teams/1
  # GET /swim_teams/1.json
  def show
    @swim_team = SwimTeam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @swim_team }
    end
  end

  # GET /swim_teams/new
  # GET /swim_teams/new.json
  def new
    @swim_team = SwimTeam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @swim_team }
    end
  end

  # GET /swim_teams/1/edit
  def edit
    @swim_team = SwimTeam.find(params[:id])
  end

  # POST /swim_teams
  # POST /swim_teams.json
  def create
    @swim_team = SwimTeam.new(params[:swim_team])

    respond_to do |format|
      if @swim_team.save
        format.html { redirect_to swim_teams_path(), notice: 'Swim team was successfully created.' }
        format.json { render json: @swim_team, status: :created, location: @swim_team }
      else
        format.html { render action: "new" }
        format.json { render json: @swim_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /swim_teams/1
  # PUT /swim_teams/1.json
  def update
    @swim_team = SwimTeam.find(params[:id])

    respond_to do |format|
      if @swim_team.update_attributes(params[:swim_team])
        format.html { redirect_to swim_teams_path(), notice: 'Swim team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @swim_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swim_teams/1
  # DELETE /swim_teams/1.json
  def destroy
    @swim_team = SwimTeam.find(params[:id])
    @swim_team.destroy

    respond_to do |format|
      format.html { redirect_to swim_teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/swim_teams_helper.rb
module SwimTeamsHelper
end

app/views/swim_teams/_form.html.erb
<%= form_for(@swim_team, :html => { :multipart => true }) do |f| %>
  <% if @swim_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swim_team.errors.count, "error") %> prohibited this swim_team from being saved:</h2>

      <ul>
      <% @swim_team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :class => 'input-block-level', :placeholder => 'Swim Team Name' %>
  </div>
  <div class="field">
    <%= f.text_area :description, :class => 'input-block-level', :placeholder => 'Description of Swim Team' %>
  </div>
  <div class="field">
    Start Age: <%= f.number_field :start_age %>
  </div>
  <div class="field">
    End Age: <%= f.number_field :end_age %>
  </div>
  <div class="field">
    Start Date: <%= f.date_select :start_date %>
  </div>
  <div class="field">
    End Date: <%= f.date_select :end_date %>
  </div>
  <div class="field">
    Start Time: <%= f.time_select :start_time %>
  </div>
  <div class="field">
    End Time: <%= f.time_select :end_time %>
  </div>

  <div class="field">
    Days of the Week: <br/>
    &nbsp;&nbsp;&nbsp;Monday: <%= f.check_box :mon %>
    &nbsp;&nbsp;&nbsp;Tuesday: <%= f.check_box :tues %>
    &nbsp;&nbsp;&nbsp;Wednesday: <%= f.check_box :wed %>
    &nbsp;&nbsp;&nbsp;Thursday: <%= f.check_box :thurs %>
    &nbsp;&nbsp;&nbsp;Friday: <%= f.check_box :fri %>
    &nbsp;&nbsp;&nbsp;Saturday: <%= f.check_box :sat %>
    &nbsp;&nbsp;&nbsp;Sunday: <%= f.check_box :sun %>
  </div>
  <div class="field">
    Number of Allowed Participants: <%= f.number_field :num_allowed_participants %>
  </div>
  <div class="field">
    Price Per Participant: <%= f.text_field :price_per_participant %>
  </div>
  <div class="field">
    Image: <%= f.file_field :photo %>
  </div>
  <div class="field">
    Active: <%= f.check_box :active %>
  </div>



  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-main' %>
  </div>
<% end %>

app/views/swim_teams/edit.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      Edit Swim Team
    </div>
  </div>


  <%= render 'form' %>

</div>

app/views/swim_teams/index.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      <% if !@staticpage.nil? %>
        <%= @staticpage.page_title %>
      <% else %>
        Swim Team
      <% end %>
    </div>
    <% if is_admin? %>
      <div class="pull-right">
        <%= link_to "New Swim Team", new_swim_team_path(), :class => "btn btn-small btn-success" %>

        <% if @staticpage.nil? %>
          <%= link_to "Edit Page", new_staticpage_path(:page_name => "SwimTeam", :page_url => "swim_teams"), :class => "btn btn-small btn-success" %>
        <% else %>
          <%= link_to "Edit Page", edit_staticpage_path(@staticpage), :class => "btn btn-small btn-success" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if !@staticpage.nil? %>
    <div style="margin:15px 0;">
      <%= simple_format(@staticpage.page_body) %>
    </div>
  <% end %>

  <div class="person_wrapper">
    <% if @swim_teams.count > 0 %>
      <% @swim_teams.each do |swim_team| 

          inactive_css = ""

          if !swim_team.active? || swim_team.start_date < Date.today
            inactive_css = "border:1px solid red;"
          end

          %>
        <div style="<%= inactive_css %> margin-bottom:10px;">
          <div class="person_left_column">
            <div>
              <%= image_tag swim_team.photo.url(:small), :class => "bordered_image" %>
            </div>
            <div class="button_wrapper">
              <% if current_user %>
                <input class="register_for_class" id="<%= swim_team.id.to_s + ',' + swim_team.class.name %>" type="checkbox" /> Add class to cart
              <% else %>
                <%= link_to 'Add class to cart', log_in_path(), :class => "btn btn-small btn-success" %>
              <% end %>
            </div>
            <% if is_admin? %>
              <div class="button_wrapper">
                <%= link_to 'Edit', edit_swim_team_path(swim_team), :class => "btn btn-small btn-warning" %> &nbsp;&nbsp; <%= link_to 'Delete', swim_team, method: :delete, data: { confirm: 'Are you sure?' }, type: "#{params[:type]}", :class => "btn btn-small btn-danger" %>
              </div>
            <% end %>
            <% if !swim_team.active %>
              <div style="color:red; font-weight:bold; text-align:center;">
                INACTIVE
              </div>
            <% end %>

            <% if swim_team.start_date < Date.today %>
              <div style="color:red; font-weight:bold; text-align:center;">
                Swim Team Started
              </div>
            <% end %>
          </div>


          <div class="person_right_column">
            <table class="table table-condensed swim_team_table" style="width:100%;">
              <tr>
                <th style="text-align:left;">Name</th>
                <th>Dates</th>
                <th>Days</th>
                <th>Time</th>
                <th>Age</th>
                <th>Price</th>
              </tr>
              <tr>
                <td class="span4" style="text-align:left;"><%= swim_team.name %></td>
                <td class="span2"><%= swim_team.start_date.strftime("%m/%d") %> - <%= swim_team.end_date.strftime("%m/%d") %></td>
                <td class="span1">
                  <% if swim_team.mon? %>Monday<% end %>
                  <% if swim_team.tues? %>Tuesday<% end %>
                  <% if swim_team.wed? %>Wednesday<% end %>
                  <% if swim_team.thurs? %>Thursday<% end %>
                  <% if swim_team.fri? %>Friday<% end %>
                  <% if swim_team.sat? %>Saturday<% end %>
                  <% if swim_team.sun? %>Sunday<% end %>
                </td>
                <td class="span3"><%= swim_team.start_time.strftime("%I:%M %p") %> - <%= swim_team.end_time.strftime("%I:%M %p")  %></td>
                <td class="span1"><%= swim_team.start_age %> - <%= swim_team.end_age %></td>
                <td class="span1"><%= number_to_currency(swim_team.price_per_participant) %></td>
              </tr>
              <tr>
                <td colspan="6" style="text-align:left;"><%= simple_format(swim_team.description) %></td>
              </tr>

            </table>
          </div>
        </div>
      <% end %>

      <div class="pull-right">
        <% if current_user %>
          <%= link_to 'CheckOut', new_payment_path(), :class => "btn btn-small btn-success" %>
        <% end %>
      </div>
    <% else %>
      <div style="margin-bottom:10px;">
        No Active Swim Teams
      </div>
    <% end %>


  </div>


</div>

app/views/swim_teams/new.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      New Swim Team
    </div>
  </div>


  <%= render 'form' %>

</div>

app/views/swim_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @swim_team.name %>
</p>

<p>
  <b>Description:</b>
  <%= @swim_team.description %>
</p>

<p>
  <b>Start age:</b>
  <%= @swim_team.start_age %>
</p>

<p>
  <b>End age:</b>
  <%= @swim_team.end_age %>
</p>

<p>
  <b>Start date:</b>
  <%= @swim_team.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @swim_team.end_date %>
</p>

<p>
  <b>Num allowed participants:</b>
  <%= @swim_team.num_allowed_participants %>
</p>

<p>
  <b>Price per participant:</b>
  <%= @swim_team.price_per_participant %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag @swim_team.photo.url(:small) %>
</p>


<%= link_to 'Edit', edit_swim_team_path(@swim_team) %> |
<%= link_to 'Back', swim_teams_path %>