config/routes.rb
CabanaClub::Application.routes.draw do

  resources :userswimlessons


  resources :swim_lessons


  resources :staticpages


  resources :member_payments


  resources :members


  resources :swim_teams


  resources :payments


  resources :meeting_notes

  match "newMN" => "meeting_notes#newMN", :as => "newMN"

  resources :meetings


  resources :people


  resources :password_resets

  resources :contacts


  match '/about' => "users#about", :as => "about"
  match '/admin' => "users#admin", :as => "admin"
  match '/payment/payments_made' => "payments#payments_made", :as => "payments_made"
  match '/add_item_to_shopping_cart' => 'users#add_item_to_shopping_cart', :via => :post
  match '/remove_item_from_shopping_cart' => 'users#remove_item_from_shopping_cart', :via => :post
  match '/remove_all_items_from_shopping_cart' => 'users#remove_all_items_from_shopping_cart', :via => :post
  match '/membership' => "users#membership", :as => "membership"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#home"

  resources :users
  resources :sessions
  resources :accounts

  get "get_accounts" => "accounts#get_accounts", :as => "get_accounts"

end

app/models/swim_lesson.rb
class SwimLesson < ActiveRecord::Base
  attr_accessible :active, :description, :end_age, :end_date, :end_time, :fri, :mon, :name, :num_allowed_participants, :price_per_participant, :sat, :start_age, :start_date, :start_time, :sun, :thurs, :tues, :wed, :photo

  has_attached_file :photo, :styles => { :icon => "95x65#", :small => "150>x150" },
  :url  => "/system/swim_lessons/:id/:style/:basename.:extension",
  :default_url => "/system/swim_lessons/default/:style/default.jpg"

  has_many :userswimlessons
  has_many :users, :through => :userswimlessons
end

app/controllers/swim_lessons_controller.rb
class SwimLessonsController < ApplicationController
  before_filter :require_admin, :except => [:index]

  # GET /swim_lessons
  # GET /swim_lessons.json
  def index

    @staticpage = Staticpage.find(:first, :conditions => ["page_name = ?", "SwimLesson"]) 

    if is_admin?
      @swim_lessons = SwimLesson.find(:all, :order => ["start_date asc, start_time asc"])
    else
      @swim_lessons = SwimLesson.find(:all, :conditions => ["active = ? && start_date >= ?", true, Date.today], :order => ["start_date asc, start_time asc"])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @swim_lessons }
    end
  end

  # GET /swim_lessons/1
  # GET /swim_lessons/1.json
  def show
    @swim_lesson = SwimLesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @swim_lesson }
    end
  end

  # GET /swim_lessons/new
  # GET /swim_lessons/new.json
  def new
    @swim_lesson = SwimLesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @swim_lesson }
    end
  end

  # GET /swim_lessons/1/edit
  def edit
    @swim_lesson = SwimLesson.find(params[:id])
  end

  # POST /swim_lessons
  # POST /swim_lessons.json
  def create
    @swim_lesson = SwimLesson.new(params[:swim_lesson])

    respond_to do |format|
      if @swim_lesson.save
        format.html { redirect_to swim_lessons_path(), notice: 'Swim lesson was successfully created.' }
        format.json { render json: @swim_lesson, status: :created, location: @swim_lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @swim_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /swim_lessons/1
  # PUT /swim_lessons/1.json
  def update
    @swim_lesson = SwimLesson.find(params[:id])

    respond_to do |format|
      if @swim_lesson.update_attributes(params[:swim_lesson])
        format.html { redirect_to swim_lessons_path(), notice: 'Swim lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @swim_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swim_lessons/1
  # DELETE /swim_lessons/1.json
  def destroy
    @swim_lesson = SwimLesson.find(params[:id])
    @swim_lesson.destroy

    respond_to do |format|
      format.html { redirect_to swim_lessons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/swim_lessons_helper.rb
module SwimLessonsHelper
end

app/views/swim_lessons/_form.html.erb
<%= form_for(@swim_lesson, :html => { :multipart => true }) do |f| %>
  <% if @swim_lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swim_lesson.errors.count, "error") %> prohibited this swim_lesson from being saved:</h2>

      <ul>
      <% @swim_lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :class => 'input-block-level', :placeholder => 'Swim Lesson Name' %>
  </div>
  <div class="field">
    <%= f.text_area :description, :class => 'input-block-level', :placeholder => 'Description of Swim Lesson' %>
  </div>
  <div class="field">
    Start Age: <%= f.number_field :start_age %>
  </div>
  <div class="field">
    End Age: <%= f.number_field :end_age %>
  </div>
  <div class="field">
    Start Date: <%= f.date_select :start_date %>
  </div>
  <div class="field">
    End Date: <%= f.date_select :end_date %>
  </div>
  <div class="field">
    Start Time: <%= f.time_select :start_time %>
  </div>
  <div class="field">
    End Time: <%= f.time_select :end_time %>
  </div>

  <div class="field">
    Days of the Week: <br/>
    &nbsp;&nbsp;&nbsp;Monday: <%= f.check_box :mon %>
    &nbsp;&nbsp;&nbsp;Tuesday: <%= f.check_box :tues %>
    &nbsp;&nbsp;&nbsp;Wednesday: <%= f.check_box :wed %>
    &nbsp;&nbsp;&nbsp;Thursday: <%= f.check_box :thurs %>
    &nbsp;&nbsp;&nbsp;Friday: <%= f.check_box :fri %>
    &nbsp;&nbsp;&nbsp;Saturday: <%= f.check_box :sat %>
    &nbsp;&nbsp;&nbsp;Sunday: <%= f.check_box :sun %>
  </div>
  <div class="field">
    Number of Allowed Participants: <%= f.number_field :num_allowed_participants %>
  </div>
  <div class="field">
    Price Per Participant: <%= f.text_field :price_per_participant %>
  </div>
  <div class="field">
    Image: <%= f.file_field :photo %>
  </div>
  <div class="field">
    Active: <%= f.check_box :active %>
  </div>



  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-main' %>
  </div>
<% end %>

app/views/swim_lessons/edit.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      Edit Swim Lesson
    </div>
  </div>


  <%= render 'form' %>

</div>

app/views/swim_lessons/index.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      <% if !@staticpage.nil? %>
        <%= @staticpage.page_title %>
      <% else %>
        Swim Lessons
      <% end %>
    </div>
    <% if is_admin? %>
      <div class="pull-right">
        <%= link_to "New Swim Lesson", new_swim_lesson_path(), :class => "btn btn-small btn-success" %>

        <% if @staticpage.nil? %>
          <%= link_to "Edit Page", new_staticpage_path(:page_name => "SwimLesson", :page_url => "swim_lessons"), :class => "btn btn-small btn-success" %>
        <% else %>
          <%= link_to "Edit Page", edit_staticpage_path(@staticpage), :class => "btn btn-small btn-success" %>
          <%= link_to 'Remove Custom Page', @staticpage, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if !@staticpage.nil? %>
    <div style="margin:15px 0;">
      <%= image_tag @staticpage.static_page_photo.url(:small), :class => "bordered_image static_page_photo" if @staticpage.static_page_photo? %>
      <%= simple_format(@staticpage.page_body) %>
    </div>
  <% end %>

  <div class="person_wrapper">
    <% if @swim_lessons.count > 0 %>
      <% @swim_lessons.each do |swim_lesson| 

          inactive_css = ""

          if !swim_lesson.active? || swim_lesson.start_date < Date.today
            inactive_css = "border:1px solid red;"
          end

          %>
        <div style="<%= inactive_css %> margin-bottom:20px;">
          <div class="person_left_column">
            <div>
              <%= image_tag swim_lesson.photo.url(:small), :class => "bordered_image" %>
            </div>
            <div class="button_wrapper">
              <% if current_user %>
                <input class="register_for_class" id="<%= swim_lesson.id.to_s + ',' + swim_lesson.class.name %>" type="checkbox" /> Add class to cart
              <% else %>
                <%= link_to 'Add class to cart', log_in_path(), :class => "btn btn-small btn-success" %>
              <% end %>
            </div>
            <% if is_admin? %>
              <div class="button_wrapper">
                <%= link_to 'Edit', edit_swim_lesson_path(swim_lesson), :class => "btn btn-small btn-warning" %> &nbsp;&nbsp; <%= link_to 'Delete', swim_lesson, method: :delete, data: { confirm: 'Are you sure?' }, type: "#{params[:type]}", :class => "btn btn-small btn-danger" %>
              </div>
            <% end %>
            <% if !swim_lesson.active %>
              <div style="color:red; font-weight:bold; text-align:center;">
                INACTIVE
              </div>
            <% end %>

            <% if swim_lesson.start_date < Date.today %>
              <div style="color:red; font-weight:bold; text-align:center;">
                Swim Lesson Started
              </div>
            <% end %>
          </div>


          <div class="person_right_column">
            <table class="table table-condensed swim_team_table" style="width:100%;">
              <tr>
                <th style="text-align:left;">Name</th>
                <th>Dates</th>
                <th>Days</th>
                <th>Time</th>
                <th>Age</th>
                <th>Price</th>
              </tr>
              <tr>
                <td class="span4" style="text-align:left;"><%= swim_lesson.name %></td>
                <td class="span2"><%= swim_lesson.start_date.strftime("%m/%d") %> - <%= swim_lesson.end_date.strftime("%m/%d") %></td>
                <td class="span1">
                  <% if swim_lesson.mon? %>Monday<% end %>
                  <% if swim_lesson.tues? %>Tuesday<% end %>
                  <% if swim_lesson.wed? %>Wednesday<% end %>
                  <% if swim_lesson.thurs? %>Thursday<% end %>
                  <% if swim_lesson.fri? %>Friday<% end %>
                  <% if swim_lesson.sat? %>Saturday<% end %>
                  <% if swim_lesson.sun? %>Sunday<% end %>
                </td>
                <td class="span3"><%= swim_lesson.start_time.strftime("%I:%M %p") %> - <%= swim_lesson.end_time.strftime("%I:%M %p")  %></td>
                <td class="span1"><%= swim_lesson.start_age %> - <%= swim_lesson.end_age %></td>
                <td class="span1"><%= number_to_currency(swim_lesson.price_per_participant) %></td>
              </tr>
              <tr>
                <td colspan="6" style="text-align:left;"><%= simple_format(swim_lesson.description) %></td>
              </tr>

            </table>
          </div>

          <% if is_admin? %>
            <div>
              <div class="person_wrapper" style="margin:0 20px 0 20px;">
                <% if swim_lesson.users.length > 0 %>
                  <h5>Users signed up for this Swim Lesson:</h5>
                  <div style="padding-left:20px;">
                    <table class="table table-condensed">
                      <tr>
                        <th>Email</th>
                        <th>Fname</th>
                        <th>Lname</th>
                        <th>Phone number</th>
                      </tr>

                      <% swim_lesson.users.each do |user| %>
                        <tr>
                          <td><%= user.email %></td>
                          <td><%= user.fname %></td>
                          <td><%= user.lname %></td>
                          <td><%= user.phone_number %></td>
                        </tr>
                      <% end %>

                    </table>
                  </div>
                <% else %>
                  <h5>No users signed up for this Swim Lesson</h5>
                <% end %>
              </div>
            </div>
          <% end %>


        </div>
      <% end %>

      <div class="pull-right">
        <% if current_user %>
          <%= link_to 'CheckOut', new_payment_path(), :class => "btn btn-small btn-success" %>
        <% end %>
      </div>
    <% else %>
      <div style="margin-bottom:10px;">
        No Active Swim Lessons
      </div>
    <% end %>


  </div>


</div>

app/views/swim_lessons/new.html.erb
<div class="bordered_wrapper">

  <div class="header_wrapper">
    <div class="main_header">
      New Swim Lesson
    </div>
  </div>


  <%= render 'form' %>

</div>

app/views/swim_lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @swim_lesson.name %>
</p>

<p>
  <b>Description:</b>
  <%= @swim_lesson.description %>
</p>

<p>
  <b>Start age:</b>
  <%= @swim_lesson.start_age %>
</p>

<p>
  <b>End age:</b>
  <%= @swim_lesson.end_age %>
</p>

<p>
  <b>Start date:</b>
  <%= @swim_lesson.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @swim_lesson.end_date %>
</p>

<p>
  <b>Num allowed participants:</b>
  <%= @swim_lesson.num_allowed_participants %>
</p>

<p>
  <b>Price per participant:</b>
  <%= @swim_lesson.price_per_participant %>
</p>

<p>
  <b>Active:</b>
  <%= @swim_lesson.active %>
</p>

<p>
  <b>Start time:</b>
  <%= @swim_lesson.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @swim_lesson.end_time %>
</p>

<p>
  <b>Mon:</b>
  <%= @swim_lesson.mon %>
</p>

<p>
  <b>Tues:</b>
  <%= @swim_lesson.tues %>
</p>

<p>
  <b>Wed:</b>
  <%= @swim_lesson.wed %>
</p>

<p>
  <b>Thurs:</b>
  <%= @swim_lesson.thurs %>
</p>

<p>
  <b>Fri:</b>
  <%= @swim_lesson.fri %>
</p>

<p>
  <b>Sat:</b>
  <%= @swim_lesson.sat %>
</p>

<p>
  <b>Sun:</b>
  <%= @swim_lesson.sun %>
</p>


<%= link_to 'Edit', edit_swim_lesson_path(@swim_lesson) %> |
<%= link_to 'Back', swim_lessons_path %>